singleQuote: true
semi: false
printWidth: 100
trailingComma: none
importOrder:
  - ^(react/(.*)$)|^(react$)
  - ^(next/(.*)$)|^(next$)
  - <THIRD_PARTY_MODULES>
  - ''
  - ^@common/(.*)$
  - ^@renderer/(.*)$
  - ''
  - '^[./]'
importOrderSeparation: false
importOrderSortSpecifiers: true
importOrderBuiltinModulesToTop: true
importOrderParserPlugins:
  - typescript
  - jsx
  - tsx
  - decorators-legacy
importOrderMergeDuplicateImports: true
importOrderCombineTypeAndValueImports: true
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
